In [1]:
import numpy as np

arr_1d=np.array([1,2,3,4,5])
print(arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
import numpy as np

py_list = [1, 2, 3, 4, 5]
print(py_list * 2)

np_array = np.array([1, 2, 3, 4, 5])
print(np_array * 2)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [6]:
import numpy as np
import time

py_list = [1, 2, 3, 4, 5]
print(py_list * 2)

np_array = np.array([1, 2, 3, 4, 5])
print(np_array * 2)

start=time.time()
py_list=[i*2 for i in py_list]
end=time.time()
print(end-start)

start=time.time()
np_array=np_array*2
end=time.time()
print(end-start)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
0.00015354156494140625
8.273124694824219e-05


### Creating Array from scratch